config/routes.rb
Demo::Application.routes.draw do
  get "love/dog"
  get "love/cat"
  get "say/hello_kitty" => "say#hello", as: 'say_hello'
  get "say/Goodbye_now" => "say#Goodbye", as: 'say_Goodbye'

  

end

app/models/animal.rb
class Animal
	def initialize(sound)
		@sound = sound
	end

	def say
		@sound
	end

	def do_sample
		sample_variable = 1
	end
end

class NewAnimalType
	CONSTANT = 1
	HANG_SO = 1
	NHIEU_HANG_SO = 1
end

dog = Animal.new("gau gau")
puts dog.say

cat = Animal.new("meo meo")
puts cat.say



begin
    nil / 1
rescue ZeroDivisionError => error
	puts "day la loi #{error.message}"
end

# Bai tap ve nha

# Viet mot class mo ta "con nguoi" co nhung thuoc tinh: "ten", "gioi tinh", "chung toc"
# co cac phuong thuc: 
# "chao" => "Xin chao, toi la <ten>"
# "gioi_thieu" => "Toi la mot <gioi_tinh> nguoi <chung_toc>"

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  	@files = Dir.glob('*')
  end

  def Goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/love_helper.rb
module LoveHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/Goodbye.html.erb
<h1>Goodbye!</h1>
<p>It was nice having you here.</p>
<p>
<%= link_to "Hello", say_hello_path %>
</p>

<p>
<%= 3 + 6 %> <br>
<%= "linh " + "de thuong" %>
<br>
<%= "Anh cu cai " + "thich an ca chua" %>
</p>

<p>
<%= 2.hour.from_now.localtime %>
</p>

app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p> What time is it?</p>
It is <%= @time %>
<p>
Say <a href="/say/Goodbye"> Goodbye </a>
</p>
<p>
<%= link_to "Goodbye", say_Goodbye_path%>
</p>

<p>
<%= @files %>
</p>

<p>
<ul>
<% for n in @files %>
	<li>file name is <%= n %> </li>
<% end %>
</ul>
</p>